In [155]:
import pandas as pd
import pickle

contracts_df = pd.read_csv('./contracts.csv', low_memory=False)
contracts_df.head(3)

,Purchase Order Description,Purchase Order (Contract) Number,Revision Number,Specification Number,Contract Type,Start Date,End Date,Approval Date,Department,Vendor Name,Vendor ID,Address 1,Address 2,City,State,Zip,Award Amount,Procurement Type,Contract PDF
0,DFSS-CORP-YS-CJI: CORP - YOUTH SERVICES - COMM...,77041,2,774638,DELEGATE AGENCY,2018-04-01T00:00:00.000,2020-12-31T00:00:00.000,2019-12-03T00:00:00.000,DEPT OF FAMILY AND SUPPORT SERVICES,CHICAGO URBAN LEAGUE DEV CORP,31311292X,4510 S MICHIGAN AVENUE EFT,NaN,CHICAGO,IL,60653-3898,150000.0,NaN,NaN
1,DFSS-ECBG-CS-PISS: PREVENTION INITIATIVE SUPPO...,106913,1,466260,DELEGATE AGENCY,2019-07-01T00:00:00.000,2020-06-30T00:00:00.000,2019-12-03T00:00:00.000,DEPT OF FAMILY AND SUPPORT SERVICES,CENTERS FOR NEW HORIZONS 01,15427701H,4150 S KING DRIVE EFT,NaN,CHICAGO,IL,60653,0.0,NaN,NaN
2,"700819: INDUSTRIAL EQUIPMENT, TOOLS, ATTACHMEN...",117383,0,700819,COMMODITIES-AVIATION,NaN,NaN,2019-12-03T00:00:00.000,DEPARTMENT OF WATER MANAGEMENT,MSC INDUSTRIAL SUPPLY CO,95881790V,DEPT CH 0075,NaN,PALATINE,IL,60155-0075,1263.0,NaN,NaN

In [156]:
cols = {}
for col in contracts_df:
    cols[col] = col.upper().replace(' ', '_')

print(cols)

{'Purchase Order Description': 'PURCHASE_ORDER_DESCRIPTION', 'Purchase Order (Contract) Number': 'PURCHASE_ORDER_(CONTRACT)_NUMBER', 'Revision Number': 'REVISION_NUMBER', 'Specification Number': 'SPECIFICATION_NUMBER', 'Contract Type': 'CONTRACT_TYPE', 'Start Date': 'START_DATE', 'End Date': 'END_DATE', 'Approval Date': 'APPROVAL_DATE', 'Department': 'DEPARTMENT', 'Vendor Name': 'VENDOR_NAME', 'Vendor ID': 'VENDOR_ID', 'Address 1': 'ADDRESS_1', 'Address 2': 'ADDRESS_2', 'City': 'CITY', 'State': 'STATE', 'Zip': 'ZIP', 'Award Amount': 'AWARD_AMOUNT', 'Procurement Type': 'PROCUREMENT_TYPE', 'Contract PDF': 'CONTRACT_PDF'}

In [157]:
contracts_df.rename(columns=cols, inplace=True)
contracts_df.head(1)

,PURCHASE_ORDER_DESCRIPTION,PURCHASE_ORDER_(CONTRACT)_NUMBER,REVISION_NUMBER,SPECIFICATION_NUMBER,CONTRACT_TYPE,START_DATE,END_DATE,APPROVAL_DATE,DEPARTMENT,VENDOR_NAME,VENDOR_ID,ADDRESS_1,ADDRESS_2,CITY,STATE,ZIP,AWARD_AMOUNT,PROCUREMENT_TYPE,CONTRACT_PDF
0,DFSS-CORP-YS-CJI: CORP - YOUTH SERVICES - COMM...,77041,2,774638,DELEGATE AGENCY,2018-04-01T00:00:00.000,2020-12-31T00:00:00.000,2019-12-03T00:00:00.000,DEPT OF FAMILY AND SUPPORT SERVICES,CHICAGO URBAN LEAGUE DEV CORP,31311292X,4510 S MICHIGAN AVENUE EFT,NaN,CHICAGO,IL,60653-3898,150000.0,NaN,NaN

In [158]:
contracts_df.isnull().sum()

PURCHASE_ORDER_DESCRIPTION            2614
PURCHASE_ORDER_(CONTRACT)_NUMBER         0
REVISION_NUMBER                          0
SPECIFICATION_NUMBER                 12222
CONTRACT_TYPE                        44747
START_DATE                           41279
END_DATE                             42387
APPROVAL_DATE                           21
DEPARTMENT                            9417
VENDOR_NAME                              0
VENDOR_ID                                0
ADDRESS_1                                1
ADDRESS_2                           124355
CITY                                   995
STATE                                    3
ZIP                                   1750
AWARD_AMOUNT                             0
PROCUREMENT_TYPE                     96430
CONTRACT_PDF                         90485
dtype: int64

In [159]:
print(contracts_df['ZIP'].value_counts())

ZIP
60607         7239
60608         4327
60606         3643
60612         2719
60610         2663
              ...
43130            1
54520            1
94703            1
49007            1
60004-1431       1
Name: count, Length: 2853, dtype: int64

In [160]:
cols = [
    'REVISION_NUMBER',
    'SPECIFICATION_NUMBER',
    'VENDOR_NAME',
    'VENDOR_ID',
    'ADDRESS_1',
    'ADDRESS_2',
    'PROCUREMENT_TYPE'
]
contracts_df.drop(columns=cols, inplace=True)
contracts_df.head(1)

,PURCHASE_ORDER_DESCRIPTION,PURCHASE_ORDER_(CONTRACT)_NUMBER,CONTRACT_TYPE,START_DATE,END_DATE,APPROVAL_DATE,DEPARTMENT,CITY,STATE,ZIP,AWARD_AMOUNT,CONTRACT_PDF
0,DFSS-CORP-YS-CJI: CORP - YOUTH SERVICES - COMM...,77041,DELEGATE AGENCY,2018-04-01T00:00:00.000,2020-12-31T00:00:00.000,2019-12-03T00:00:00.000,DEPT OF FAMILY AND SUPPORT SERVICES,CHICAGO,IL,60653-3898,150000.0,NaN

In [161]:
print(contracts_df['START_DATE'][1])
print(type(contracts_df['START_DATE'][1]))

contracts_df['START_DATE'] = pd.to_datetime(contracts_df['START_DATE'], errors='coerce').dt.strftime('%d/%m/%Y')
contracts_df['START_DATE'] = pd.to_datetime(contracts_df['START_DATE'], errors='coerce')
print('-------------MODIFIED--------------')
print(contracts_df['START_DATE'][1])
print(type(contracts_df['START_DATE'][1]))

2019-07-01T00:00:00.000
<class 'str'>
-------------MODIFIED--------------
2019-01-07 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [162]:
contracts_df['END_DATE'] = pd.to_datetime(contracts_df['END_DATE'], errors='coerce').dt.strftime('%d/%m/%Y')
contracts_df['END_DATE'] = pd.to_datetime(contracts_df['END_DATE'], errors='coerce', dayfirst=True)
print(type(contracts_df['END_DATE'][1]))

contracts_df.head(1)

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

,PURCHASE_ORDER_DESCRIPTION,PURCHASE_ORDER_(CONTRACT)_NUMBER,CONTRACT_TYPE,START_DATE,END_DATE,APPROVAL_DATE,DEPARTMENT,CITY,STATE,ZIP,AWARD_AMOUNT,CONTRACT_PDF
0,DFSS-CORP-YS-CJI: CORP - YOUTH SERVICES - COMM...,77041,DELEGATE AGENCY,2018-01-04,2020-12-31,2019-12-03T00:00:00.000,DEPT OF FAMILY AND SUPPORT SERVICES,CHICAGO,IL,60653-3898,150000.0,NaN

In [163]:
with open('contracts.pkl', mode='wb') as f:
    pickle.dump(contracts_df, f)